# pull the node js image base upon alpine image run time environemnt is ready 
FROM node:latest
# copy app.js file into image in current path. 
COPY app.js .
# open the command and run app.js file in node js image 
CMD [ "node","app.js" ]
